spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        ddl_auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    root: INFO
    com.caixabank: DEBUG
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor: INFO